# Generated by Django 5.2 on 2025-04-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                    ("Accepted", "Accepted"),
                    ("New", "New"),
                ],
                default="New",
                max_length=10,
            ),
        ),
    ]
